build: enable support for Kotlin multiplatform subprojects
AlchemistSimulator/Alchemist pull request #1694
Opened 2022-11-21 17:51 UTC by AngeloFilaseta

It will be possible to include a multiplatform subproject in the repository using the kotlin("multiplatform") plugin and a "multiplatform" property.

2022-11-21 18:12 UTC, DanySK commented
@AngeloFilaseta for future commits, the simple present is preferable.
Is it a problem for you if I squash this in after review?

2022-11-21 18:17 UTC, AngeloFilaseta commented
@DanySK Of course, no problem for the squash. I'll be more careful for commit messages.

2022-11-21 18:17 UTC, DanySK requested changes
Two very minor changes / discussions to be solved before merge.

2022-11-21 18:18 UTC, AngeloFilaseta commented on buildSrc/src/main/kotlin/Util.kt
> +        this.hasProperty("multiplatform") && this.property("multiplatform") == "true"
Perfect, will do.

2022-11-21 18:26 UTC, AngeloFilaseta commented on alchemist-full/build.gradle.kts
> +    rootProject.subprojects.filterNot { it == project || it.isMultiplatform }.forEach {
I think it is possible to achieve this goal, but not by adding it to the dependencies like this. I'll check for some possible solutions. The jar generated by my project contains the frontend compiled code too, as it serves it to the clients. However, this is a special case. A multiplatform project in the future could build its jar or used the compiled code in a different way. I'll think about it tomorrow.

2022-11-23 15:35 UTC, DanySK approved these changes

2022-11-23 15:39 UTC, merged

2022-12-02 20:01 UTC, DanySK commented
:tada: This PR is included in version 24.1.16 :tada:

The release is available on:
- `24.1.16`
- [GitHub release](https://github.com/AlchemistSimulator/Alchemist/releases/tag/24.1.16)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: