Add integration with MultiVesta
AlchemistSimulator/Alchemist pull request #1978
Opened 2023-02-17 06:42 UTC by magnanig

This will add the module alchemist-multivesta-adapter to integrate Alchemist with the statistical tool MultiVesta.
The class AlchemistSimState has been moved to dist folder since it contains dependencies from multivesta.jar (that is not tracked).
Who wants to use the simulator with MultiVesta has to include both multivesta.jar (in java path) and AlchemistSimState class (in their jvm project).

2023-02-17 07:24 UTC, magnanig commented on alchemist-multivesta-adapter/src/main/kotlin/it/unibo/alchemist/multivesta/adapter/AlchemistSimulationAdapter.kt
> +            } catch (e: Exception) {
@sonatype-lift ignore

2023-02-17 07:24 UTC, magnanig commented on alchemist-multivesta-adapter/src/main/kotlin/it/unibo/alchemist/multivesta/adapter/AlchemistMultiVesta.kt
> +        } catch (e: Exception) {
@sonatype-lift ignore

2023-02-17 09:12 UTC, DanySK requested changes
We need the following for this PR to be merged:
1. A detailed explanation, in form of a webpage "howto" page, of how to use this module to run Multivesta
2. We need the missing class. The problem is that, of course, it refers to parts of code that are available only in the JAR. The strategy here could be to rewrite it using reflection, so that it can compile, and requires only the jar to be added at runtime.

2023-02-17 09:14 UTC, DanySK commented
@magnanig are you okay if I enable auto-rebase on this branch? Would you prefer automerge (that would mean that this PR, once ready, will be squashed in instead of being rebased).

2023-02-17 09:31 UTC, DanySK commented on alchemist-multivesta-adapter/src/main/kotlin/it/unibo/alchemist/multivesta/adapter/AlchemistSimulationAdapter.kt
> +            } catch (e: Exception) {
@magnanig nope :)
We need to fix stuff, or to explain very well, with a comment in code, why we are not fixing it

@sonatype-lift unignore

2023-02-17 09:31 UTC, DanySK commented on alchemist-multivesta-adapter/src/main/kotlin/it/unibo/alchemist/multivesta/adapter/AlchemistMultiVesta.kt
> +        } catch (e: Exception) {
@magnanig nope :)
We need to fix stuff, or to explain very well, with a comment in code, why we are not fixing it

@sonatype-lift unignore

2023-02-17 20:52 UTC, magnanig commented on alchemist-multivesta-adapter/src/main/kotlin/it/unibo/alchemist/multivesta/adapter/AlchemistMultiVesta.kt
> +        } catch (e: Exception) {
Yes, I have fixed it in my repo, but since it wasn’t a bug I didn’t want stop the PR :)
Then, I’ll send a new PR with the new requirements

2023-02-17 20:57 UTC, magnanig commented
> @magnanig are you okay if I enable auto-rebase on this branch? Would you prefer automerge (that would mean that this PR, once ready, will be squashed in instead of being rebased).

Yes, auto-rebase is ok 👍

2023-02-17 21:08 UTC, magnanig commented
> We need the following for this PR to be merged:
> 
> 1. A detailed explanation, in form of a webpage "howto" page, of how to use this module to run Multivesta
> 2. We need the missing class. The problem is that, of course, it refers to parts of code that are available only in the JAR. The strategy here could be to rewrite it using reflection, so that it can compile, and requires only the jar to be added at runtime.

Ok for the point 1, but for the second I cant’t since that class has to extend from an abstract class defined inside the jar. I don’t think I can extend that class from a class obtained via reflection, can’t I?

2023-02-18 09:57 UTC, DanySK commented
> Ok for the point 1, but for the second I cant’t since that class has to extend from an abstract class defined inside the jar. I don’t think I can extend that class from a class obtained via reflection, can’t I?

You cannot in pure Java, indeed. You can do so for interfaces via [dynamic proxies](https://docs.oracle.com/javase/8/docs/technotes/guides/reflection/proxy.html). If you have an abstract class, the only way is bytecode manipulation, e.g. via [ByteBuddy](https://bytebuddy.net/#/). Spend a couple of hours and try to understand if you can make this work, if it is overkill, we'll accept the class absence for now

2023-02-19 06:35 UTC, magnanig commented
> > Ok for the point 1, but for the second I cant’t since that class has to extend from an abstract class defined inside the jar. I don’t think I can extend that class from a class obtained via reflection, can’t I?
> 
> You cannot in pure Java, indeed. You can do so for interfaces via [dynamic proxies](https://docs.oracle.com/javase/8/docs/technotes/guides/reflection/proxy.html). If you have an abstract class, the only way is bytecode manipulation, e.g. via [ByteBuddy](https://bytebuddy.net/#/). Spend a couple of hours and try to understand if you can make this work, if it is overkill, we'll accept the class absence for now

I've read the ByteBuddy guide and I've concluded I can rewrite my class via bytecode manipulation, but then there's a problem on how multivesta loads such class: I've decoded bytecode starting from the multivesta main and I've found these lines
```java
Class<?> clazz = Class.forName(this.classNameOfStateDescriptor);
Constructor<?> constructor = clazz.getConstructor(param.getArgumentClasses());
this.state = (NewState)constructor.newInstance(param.getArguments());
```
where `this.classNameOfStateDescriptor` is the name of my class that multivesta expects to be a `NewState`.
The problem is that if I define a class with Byte Buddy, it can't be loaded with just `Class.forName`, since it is not in classpath. To do that, I've found the following solution:
1. save the manipulated class in a .class file (I can do it)
2. use a custom ClassLoader starting from the directory containing that .class (but I can't do it since I can't access multivesta sources)

To avoid point 2, I've found I can set a global loader to be used as default, with
`Thread.currentThread().contextClassLoader = customClassLoader `, but I think that could be a problem for the whole application then.

2023-02-21 15:22 UTC, DanySK commented
@magnanig I see no progress here; the build must pass for the PR to be merged (and the experiment to be built).

2023-02-22 07:55 UTC, magnanig commented
> @magnanig I see no progress here; the build must pass for the PR to be merged (and the experiment to be built).

Yes, at the moment I’m executing it locally because I’ve found a bug in the class extended with Byte Buddy (it is related to the field I added via byte code manipulation). Today I’ll see if I can fix it, otherwise we’ll let the class as in the original PR.

2023-03-13 13:31 UTC, DanySK commented
Removing autorebase, as this PR has a ton of merge commits. Will be squashed in once ready.

2023-03-17 08:53 UTC, merged

2023-03-17 11:34 UTC, DanySK commented
:tada: This PR is included in version 25.15.0 :tada:

The release is available on:
- `25.15.0`
- [GitHub release](https://github.com/AlchemistSimulator/Alchemist/releases/tag/25.15.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: