fix(alchemist-ui-tooling): adjust the initial GUI centering on the map
AlchemistSimulator/Alchemist pull request #2842
Opened 2023-11-10 16:44 UTC by DenGuzawr22

Fix the error when the points on the map were not zoomed properly on simulation start.
Before fix: 
![Screenshot 2023-11-10 172014](https://github.com/AlchemistSimulator/Alchemist/assets/55553082/46db88c8-a07d-40e3-a617-064a6f3e09d9)
After fix:
![Screenshot 2023-11-10 172152](https://github.com/AlchemistSimulator/Alchemist/assets/55553082/5824ca30-fb69-41ee-994e-2c4ba134345c)

2023-11-10 17:25 UTC, DenGuzawr22 commented
This is an hotfix. Probably could be better override the `center()` method  in `MapWormhole`

2023-11-10 18:21 UTC, DenGuzawr22 commented
The build is fail with error:

```
  FAILURE: Build failed with an exception.
  
  * What went wrong:
  Execution failed for task ':alchemist-ui-tooling:pmdMain'.
  > A failure occurred while executing org.gradle.api.plugins.quality.internal.PmdAction
     > 2 PMD rule violations were found. See the report at: file:///home/runner/work/Alchemist/Alchemist/alchemist-ui-tooling/build/reports/pmd/main.html
  
  BUILD FAILED in 2m 41s
````
I tried to execute the task `alchemist-ui-tooling:pmdMain`  on my PC but I get empty report

2023-11-11 20:10 UTC, DanySK requested changes

2023-11-11 20:10 UTC, DanySK commented on alchemist-ui-tooling/src/main/java/it/unibo/alchemist/boundary/ui/impl/AbstractWormhole2D.java
> +                : from((off[0] + size[0] / 2), (off[1] + size[1] / 2));
```suggestion
                : from(off[0] + size[0] / 2, off[1] + size[1] / 2);
```

2023-11-11 20:10 UTC, DanySK commented on alchemist-ui-tooling/src/main/java/it/unibo/alchemist/boundary/ui/impl/AbstractWormhole2D.java
> +                : from((off[0] + size[0] / 2), (off[1] + size[1] / 2));
Useless parentheses make PMD sad

2023-11-11 21:54 UTC, merged